name: backend_workflow CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
defaults:
  run:
    working-directory: backend

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
    
    - name: Install dependencies
      run: npm ci
      
    - name: Start server
      run: npm start
