name: backend_workflow CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
defaults:
  run:
    working-directory: backend

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: node
    
    steps:
   
    - name: Checkout
      uses: actions/checkout@v3
      
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    
    - name: Install Dependencies
      run: npm install
      
#     - name: Tests
#       run: npm start
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERUSERNAME }}
        password: ${{ secrets.DOCKERTOKEN }}
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Docker/Dockerfile
        push: true
        tags: ${{ secrets.DOCKERUSERNAME }}/clockbox:latest
