name: frontend_workflow CI

on:
  push:
    branches: [ "main" ]
    
jobs:
  start:
   runs-on: ubuntu-latest 

   steps:
   - name: Checkout out repo.
     uses: actions/checkout@v2
  
   - name: Running commands to execute script
     uses: appleboy/ssh-action@master
     with:
       key: ${{ secrets.EC2_PRIV_KEY }}
       #USER_NAME: ${{ secrets.EC2_USERNAME }}
       #HOSTNAME: ${{ secrets.EC2_HOST }}
       username: ${{ secrets.AWS_USERNAME }}
       aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
       aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
       host: ${{ secrets.HOST  }}
       aws-region: ${{ secrets.AWS_REGION  }}
       instance-ids: ${{ secrets.INSTANCE_ID  }}
       port: 22
       #command: /bin/sh ./deploy.sh
       script: |
         ll
         exit
          
    
