name: frontend_workflow CI

on:
  push:
    branches: [ "main" ]
    
jobs:
  start:
   runs-on: ubuntu-latest 

   steps:
   - name: Checkout out repo.
     uses: actions/checkout@v3
  
   - name: Running commands to execute script
     uses: easingthemes/ssh-deploy@main
     env:
       SSH_PRIVATE_KEY: ${{ secrets.EC2_PRIV_KEY }}
       REMOTE_USER: ubuntu
       REMOTE_HOST: ec2-54-68-135-154.us-west-2.compute.amazonaws.com
       SCRIPT_AFTER: |
         /home/ubuntu/InventoryKeeper/frontend/deploy.sh
         
         
         
         
          
    
