name: frontend_workflow CI

on:
  push:
    branches: [ "main" ]
    
jobs:
  start:
   runs-on: ubuntu-latest 

   steps:
   - name: Checkout out repo.
     uses: actions/checkout@v2
  
   - name: Running commands to execute script
     uses: appleboy/ssh-action@v0.1.9
     with:
       key: ${{ secrets.EC2_PRIV_KEY }}
       #USER_NAME: ${{ secrets.EC2_USERNAME }}
       #HOSTNAME: ${{ secrets.EC2_HOST }}
       username: ecsInstanceRole
       #aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
       #aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
       host: ec2-52-42-50-89.us-west-2.compute.amazonaws.com
       aws-region: us-west-2
       #instance-ids: ${{ secrets.INSTANCE_ID  }}
       port: 22
       #command: /bin/sh ./deploy.sh
       script: |
         ll
         exit
         
         
          
    
