name: frontend_workflow CI

on:
  push:
    branches: [ "main" ]
    
jobs:
  start:
   runs-on: ubuntu-latest 

   steps:
   - name: Checkout out repo.
     uses: actions/checkout@v2

   - name: Executing remote commands
     uses: appleboy/ssh-action@v0.1.9
     with:
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         host: ${{ secrets.HOST  }}
         aws-region: ${{ secrets.AWS_REGION  }}
         instance-ids: ${{ secrets.INSTANCE_ID  }}
         command: /bin/sh ./deploy.sh
    
